---
author: 
  name: "Dr Timothy Davies"
  affiliation: "Department of Electronic and Electrical Engineering"
date: "10/03/2024"
number-sections: false
---

# Microcontroller Programming Laboratory {#sec-micros-lab}

Our colleague Dr Timothy Davies designed the Microcontroller Programming laboratory to teach you the fundamentals of programming microcontrollers. 

Associated with this Laboratory is a Getting Started Guide, and five microcontroller experiments designed to give you the experience of programming a microprocessor (in this case an [Arduino Nano](https://store.arduino.cc/products/arduino-nano) based on the [Atmel ATMega32 microcontroller](https://www.microchip.com/en-us/product/ATmega32)) in the [C-language](https://en.wikipedia.org/wiki/C_(programming_language)) and interfacing it to digital and analogue signals. We expect you to record the results of your experiments using a Lab Diary which will be submitted in at the end of the laboratory for assessment. 

## Lab Experiments

The Microcontroller Laboratory consists of a getting started introduction, plus the five assessable experiments listed below.

* @sec-getting-started
* @sec-lab-1
* @sec-lab-2
* @sec-lab-3
* @sec-lab-4
* @sec-lab-5

## Assessment of the Microcontroller Laboratory

The mark for each of the experiments is a maximum of five points, making a total of 25 marks &ndash; 25% of the assessment for the whole module.

Assessment will be based on a **Laboratory (Lab) Diary**. Many other lab-based modules are assessed this way, including EG-152 Electronic Circuits next term, and the two practical labs in second year, EGA222 and EGA223.

## About the Lab Diary {#sec-lab-diary}

What is a laboratory diary?

In the &ldquo;old days&rdquo; this would have taken the form of a hard-backed notebook, called a *logbook*, and all results, calculations and other details of the experiments would be meticulously written in the logbook. This is the 21st Century, and we now use an electronic logbook which we call a *Lab Diary*.

The lab diary takes the form of a Word document or similar, in which all the details of an experiment are recorded. This might include tables of results, graphs or calculations based on the results, screen shots from the Lab PC or the R&amp;S oscilloscope, photos of the equipment, anything that helps someone reading the diary (including your yourself) to see what was done. In addition, if you are asked to write a report on a particular subject (for example, in EG-152, EGA222 and EGA223) then the lab diary is the source of information for each experiment. You should not need to go back to the laboratory to repeat parts of the experiment. More information about lab diaries, including an example and template is given on Canvas on the page [✅ To Do: Obtain and Keep a Lab Diary 📓](https://canvas.swansea.ac.uk/courses/52902/pages/to-do-obtain-and-keep-a-lab-diary?module_item_id=2882101).

The script for each of the experiments will tell you what is required for each experiment. In general, this will be programme listings (properly formatted and with copious comments, of course!) and some measurements and calculations based on the results. The lab diary will be submitted later in the term for assessment. It recommended that you convert the submitted version of the diary to pdf, so that we see your document without changes caused by printer drivers, different versions of WORD, and so on.

## Questions and Discussion

If you have questions about any aspect of the Microcontroller Programming Laboratory, please visit the discussion board on Canvas:[💬 ❓ 🧪 Discussion and Questions about the Microcontroller Programming Lab Exercises](hhttps://canvas.swansea.ac.uk/courses/52902/discussion_topics/468325). See also [💬 ❓ 📓 Discussion and Questions about Lab Diaries](https://canvas.swansea.ac.uk/courses/52902/discussion_topics/468326).

## Good luck!

Good luck with the EG-151 microcontroller programming experiments!</p>
<ul style="list-style-type: square;">
    <li>Dr. Chris Jobling, Module Coordinator</li>
    <li>Dr. Timothy Davies, Creator of the Lab</li>
    <li>Dr. Ben Clifford, Former Module Lecturer</li>
    <li>Dr. Hayder Jahanger, Module Lecturer</li>
</ul>
