---
author: 
  name: "Dr Timothy Davies"
  affiliation: "Department of Electronic and Electrical Engineering"
date: "10/03/2024"
number-sections: false
---

# Laboratory Work in the Department of Electronic and Electrical Engineering {#sec-depteee-labwork}

The Electronics Laboratory was completely refurbished with new equipment in August 2015, following the move to the Bay Campus. The Laboratory is used extensively for practical work in the first and second years of the Electronic and Electrical Engineering degree programmes. For example, depending on your degree programme, in the first year of your studies, you will take part in the following activities in the Teaching Laboratory:

- **EG-143 Digital Design** experiments on combinatorial logic using MULTISIM.
- **EG-151 Microcontrollers**, a series of experiments on the use of microcontrollers.
- **EG-152 Analogue Design**, a programme of experiments to design a function generator.

In addition, there will be computer-based exercises to support some of the lecture courses. You may already be familiar with voltmeters, oscilloscopes, and other basic instruments. The objective of this exercise is to allow everyone to use the laboratory instruments in a straightforward experiment followed by a construction task.
