# EG-151 Microcontrollers {.unnumbered}
## Croeso/Welcome

EG-151 Microcontrollers is a first year engineering course for those studying Electrical and Electronic Engineering and General Engineering which introduces basic microcontroller structure and operation designed to teach you both theoretical and practical skills in microcontrollers. It consists of an introduction to the Electronic and Electrical Engineering laboratory, a lecture course on the architecture and operation of the Atmel ATmega328 microcontroller (from Microchip Technology), and a series of Arduino programming laboratories culminating in a mini-project in which you will apply their experience to a simple practical problem.

In the website version of this textbook, the table of contents is in the left sidebar and the page contents is in the right sidebar.

## Tour of the Canvas site {.unnumbered}

During the first class meeting we will introduce this online textbook and how the course materials are presented to you via Canvas.

## PDF Version of this Web Site {.unnumbered}

There is a version of this site that is published as a textbook in PDF form. It can be downloaded from [cpjobling.github.io/eg-151-textbook/eg-151-microcontrollers.pdf](https://cpjobling.github.io/eg-151-textbook/eg-151-microcontrollers.pdf).

The PDF file linked to this page is updated automatically when the website is updated. It is also linked to the Canvas site. Please be aware that once downloaded, the PDF will no longer tack the website so you should always download the latest version before using it.


## Citing this Document {.unnumbered}
When referencing this document please use the following format based on the library supported [Swansea Vancouver Style](https://libguides.swansea.ac.uk/Vancouver):

> Jobling, C.P., Jahanger, H., Davies, T, Clifford, B. EG-151 Microcontrollers [Internet]. Swansea: Swansea University; 2024 August. [cited 2024 Mmm dd]; Available from; https://cpjobling.github.io/eg-151-textbook.

To cite a chapter, e.g. for a lab exercise, use the more precise citation, such as:

> Jobling, C.P., Jahanger, H., Davies, T, Clifford, B. Experiment 1: Binary Counter [Internet]. Swansea: Swansea University; 2024 August. EG-151 Microcontrollers [Internet]; 2024 August [cited 2024 Mmm dd]; [1 screen]. Available from; https://cpjobling.github.io/eg-151-textbook/labs/lab01/index.html.

## Colophon {.unnumbereD}

This is a Quarto book.

To learn more about Quarto books visit <https://quarto.org/docs/books>.
