# Course Delivery Method {.unnumbered #course_delivery}

EG–151 will employ a blended approach to delivery using the Canvas Digital Learning Platform for on-campus and self-directed online activity, with live on-campus activities each week.

## Live learning activities

See the Canvas calendar for timings of the live activities.

### Lectures and Office Hours

There will be one lecture a week on **Tuesday** at **11:00 am** on the architecture of the target microcontroller. This will be delivered on-campus and will be supported by on-demand after-class formative tests which aim to reinforce the knowledge gained in lectures by means of [retrieval practice](https://youtu.be/gncl5Fn7CJ4).

In addition, there will be an online office hour at **1:00 pm on Tuesday** for group activities in support of the lecture course which is designed to address the areas of difficulty that have been identified by the formative tests. 

The resources for the lecture course are arranged by week in [modules](https://community.canvaslms.com/t5/Canvas-Basics-Guide/What-are-Modules/ta-p/6) on Canvas and start at [Week 1: Introduction to Microcontrollers and Microcontroller Architecture](https://canvas.swansea.ac.uk/courses/52902/modules#module_376451).

### Laboratory activities

There will be two two-hour lab sessions per week on **Thursday** **10-12** and **Friday** **10-12**. Lab sessions are compulsory, and should you need a Supplementary (resit) assessment in August you must have achieved 80% attendance to qualify for a resit attempt.

#### Laboratory introduction

Laboratory sessions during the first four weeks of term will be used for a laboratory introduction exercise.

The laboratory introduction is COMPULSORY and must be passed before you can continue to work in the laboratory.

Components of the laboratory introduction are as follows:

* Health and safety and safe working in the electronics laboratory
* Breadboard construction exercise
* Circuit simulation exercise using National Instruments Multisim
* Soldering exercise

The maximum mark for the laboratory introduction is 15 awarded as follows:

* Testing of circuit using plug-in breadboard and National Multisim and answers to questions at the end of the laboratory introduction script – Max. 10 marks - Assessed by Lab Diary and a Canvas quiz.
* Construction of Tic-Tac(R) box continuity tester – Max. 5 marks.

Marking is done and feedback is given by the module coordinator and the chief electronics technician.

The course materials and guidance for the lab introduction module start at module [EG-151: Laboratory Introduction](https://canvas.swansea.ac.uk/courses/52902/modules#module_376450) on Canvas.

#### Microcontroller programming laboratories

There will be two two-hour microntroller programming lab sessions per week, and these will begin once the lab introduction has been completed which will be the end of week 4 at the latest.

The laboratory work will be assessed by means of a lab diary worth 20% of the module marks. The lab diary is to be updated during the lab sessions and will be submitted via a Canvas submission point in November. 

The Microcontroller laboratories are found in the [Microcontrollers Laboratory](https://canvas.swansea.ac.uk/courses/52902/modules#module_376463) module on Canvas.

#### Mini project

There will be a mini project which is worth 30% of the marks and will be assessed by a demonstration of the completed project and a short report. The project is designed to be carried out using the resources of the laboratory kit, however additional components e.g. LEDs, resistors, push buttons and so on can be requested from the staff. A program will be provided as a starting point, and you will be required to add additional features as suggested in the project briefing. The mini project will be published in the [Mini Projects 2024-2025](https://canvas.swansea.ac.uk/courses/52902/modules#module_376465) module on Canvas.

We anticipate starting the mini project at the start of week 9.

## On-demand learning activities

Knowledge and understanding will be increased via retrieval practice based on weekly formative tests delivered in Canvas.

## Class test

The lecture course and the laboratory work will be assessed by an online class test worth 35%. We anticipate that the class test will be held between  **11 am -- 1 pm Tuesday 3rd December in Y Twyni PC Lab 104** in Week 10 with a resit being held in week commencing 20th January 2025.

## Laboratory training requirements

It is an accreditation requirement that you have demonstrated competence in **C12 Workshop and practical skills** [#ahep 4, p. 36].
To demonstrate this, you are required to keep a full record of attendance and the completion of all lab exercises in your lab diary. 
These will be regularly evaluated and signed off by the laboratory support staff during the lab sessions. In addition, 
laboratory attendance is compulsory, and the department requires that each student has achieved at least 80% attendance 
(18 of 22 available sessions) in the lab. Catch-up sessions are provided for labs missed for valid reasons.

To pass the module you must pass laboratory training requirements.
